"""
SRS Review Report Renderer
Converts structured ReviewResult JSON into a formatted markdown report.
"""

from datetime import datetime
from pathlib import Path
from typing import Dict, Optional


# Dimension weights aligned with SCORING_CRITERIA.md
DIMENSION_WEIGHTS = {
    "D1": {"name": "Purpose & Scope Clarity", "weight": 0.10},
    "D2": {"name": "Stakeholder & User Requirements", "weight": 0.10},
    "D3": {"name": "Functional Requirements", "weight": 0.15},
    "D4": {"name": "Non-Functional Requirements", "weight": 0.12},
    "D5": {"name": "System Architecture & Constraints", "weight": 0.10},
    "D6": {"name": "Data Requirements", "weight": 0.08},
    "D7": {"name": "Use Cases & Scenarios", "weight": 0.12},
    "D8": {"name": "Acceptance Criteria & Testing", "weight": 0.10},
    "D9": {"name": "Traceability & Consistency", "weight": 0.08},
    "D10": {"name": "Document Quality & Standards", "weight": 0.05},
}

VERDICT_MAP = [
    (96, "Xuất sắc — Production-ready"),
    (85, "Tốt — Solid foundation"),
    (70, "Cần cải thiện — Có lỗ hổng"),
    (50, "Yếu — Cần viết lại"),
    (0, "Nghiêm trọng — Bắt đầu lại"),
]

STATUS_EMOJI = {
    "excellent": "🟢",
    "good": "🟢",
    "needs_improvement": "🟡",
    "weak": "🔴",
    "critical": "🔴",
}


def get_verdict(score: float) -> str:
    """Map a total score to a verdict string."""
    for threshold, label in VERDICT_MAP:
        if score >= threshold:
            return label
    return VERDICT_MAP[-1][1]


def get_status_emoji(score: float) -> str:
    """Return an emoji indicator for a dimension score."""
    if score >= 85:
        return "✅"
    elif score >= 70:
        return "⚠️"
    else:
        return "❌"


def recalculate_score(sections: list) -> float:
    """
    Recalculate the weighted total from per-dimension scores.
    Expects sections list from LLM JSON with 'score' and dimension ID in title.
    """
    total = 0.0
    for section in sections:
        title = section.get("title", "")
        score = section.get("score", 0)
        # Extract dimension ID (e.g., "D1" from "D1 — Purpose & Scope")
        dim_id = title.split("—")[0].split("–")[0].strip().upper()
        # Remove Vietnamese prefix if present
        for key in DIMENSION_WEIGHTS:
            if key in dim_id:
                dim_id = key
                break
        weight = DIMENSION_WEIGHTS.get(dim_id, {}).get("weight", 0)
        total += score * weight
    return round(total, 1)


class ReportRenderer:
    """Renders a structured ReviewResult into a markdown report."""

    def __init__(self, reviewer: str = "SRS Review AI", mode: str = "Standard"):
        self.reviewer = reviewer
        self.mode = mode

    def render(self, review_result: Dict, srs_filename: str = "Unknown") -> str:
        """
        Render review result JSON into a markdown report string.

        Args:
            review_result: Parsed JSON from LLM (matches SRSAnalysis output schema).
            srs_filename: Name of the reviewed SRS file.

        Returns:
            Markdown report string.
        """
        if "error" in review_result:
            return self._render_error(review_result, srs_filename)

        total_score = review_result.get("totalScore", 0)
        verdict = review_result.get("verdict", get_verdict(total_score))
        sections = review_result.get("sections", [])

        # Recalculate score for validation
        recalc = recalculate_score(sections)
        score_note = ""
        if abs(recalc - total_score) > 2:
            score_note = f"\n> ⚠️ Score discrepancy: LLM reported {total_score}, recalculated {recalc}\n"

        report_lines = [
            f"# SRS Review: {srs_filename}",
            "",
            f"**Reviewer**: {self.reviewer}  ",
            f"**Date**: {datetime.now().strftime('%Y-%m-%d %H:%M')}  ",
            f"**Review Mode**: {self.mode}  ",
            f"**Total Score**: {total_score}/100 {get_status_emoji(total_score)}  ",
            f"**Verdict**: {verdict}",
            score_note,
            "---",
            "",
            "## Executive Summary",
            "",
            self._executive_summary(total_score, sections),
            "",
            "---",
            "",
            "## Per-Dimension Breakdown",
            "",
        ]

        for section in sections:
            report_lines.append(self._render_dimension(section))

        report_lines.extend([
            "---",
            "",
            "## Next Steps",
            "",
            "- [ ] Address all ❌ critical dimensions (score < 70)",
            "- [ ] Improve ⚠️ dimensions (score 70–84)",
            "- [ ] Re-review after revisions",
            "",
            "---",
            "",
            f"*Generated by {self.reviewer} — {self.mode} Review Mode*",
        ])

        return "\n".join(report_lines)

    def save(
        self,
        report: str,
        output_path: Optional[str] = None,
        reviews_dir: str = "reviews",
    ) -> Path:
        """
        Save the rendered report to a file.

        Args:
            report: Markdown report string.
            output_path: Custom output file path. If None, auto-generates.
            reviews_dir: Directory for auto-generated filenames.

        Returns:
            Path to the saved file.
        """
        if output_path:
            path = Path(output_path)
        else:
            dir_path = Path(reviews_dir)
            dir_path.mkdir(parents=True, exist_ok=True)
            timestamp = datetime.now().strftime("%Y-%m-%d-%H%M")
            path = dir_path / f"review-{timestamp}.md"

        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(report, encoding="utf-8")
        return path

    def _executive_summary(self, total_score: float, sections: list) -> str:
        """Generate an executive summary paragraph."""
        low_dims = [s for s in sections if s.get("score", 0) < 70]
        high_dims = [s for s in sections if s.get("score", 0) >= 85]

        summary = f"The SRS achieved a total weighted score of **{total_score}/100**. "

        if total_score >= 85:
            summary += "The document meets the quality threshold and is **Ready for Development**. "
        else:
            summary += "The document **Needs Revision** before proceeding. "

        if low_dims:
            dim_names = ", ".join(
                s.get("title", "Unknown").split("—")[-1].strip()
                for s in low_dims
            )
            summary += f"Critical gaps found in: {dim_names}. "

        if high_dims:
            summary += f"{len(high_dims)} dimension(s) scored well (≥85)."

        return summary

    def _render_dimension(self, section: Dict) -> str:
        """Render a single dimension into markdown."""
        title = section.get("title", "Unknown")
        score = section.get("score", 0)
        emoji = get_status_emoji(score)

        lines = [
            f"### {title} — {score}/100 {emoji}",
            "",
        ]

        # Praise
        praise_list = section.get("praise", [])
        if praise_list:
            lines.append("**Strengths:**")
            for p in praise_list:
                praise_text = p.get("praise", p) if isinstance(p, dict) else str(p)
                lines.append(f"- ✅ {praise_text}")
            lines.append("")

        # Issues
        issues_list = section.get("issues", [])
        if issues_list:
            lines.append("**Issues:**")
            for issue in issues_list:
                if isinstance(issue, dict):
                    sev = issue.get("severity", "minor")
                    text = issue.get("issue", "")
                    sev_icon = "🔴" if sev in ("critical", "major") else "🟡"
                    lines.append(f"- {sev_icon} [{sev}] {text}")
                else:
                    lines.append(f"- 🟡 {issue}")
            lines.append("")

        # Suggestions
        suggestions = section.get("suggestions", [])
        if suggestions:
            lines.append("**Suggestions:**")
            for s in suggestions:
                lines.append(f"- 💡 {s}")
            lines.append("")

        return "\n".join(lines)

    def _render_error(self, result: Dict, srs_filename: str) -> str:
        """Render an error report."""
        return "\n".join([
            f"# SRS Review: {srs_filename}",
            "",
            f"**Date**: {datetime.now().strftime('%Y-%m-%d %H:%M')}  ",
            f"**Status**: ❌ Review Failed",
            "",
            "## Error",
            "",
            f"```\n{result.get('error', 'Unknown error')}\n```",
        ])
